name: Test Partner Driver

on:
  workflow_call:
    inputs:
      DRIVER:
        description: 'Driver to use'
        type: string
        required: true
      MB_VERSION:
        type: string
        required: true
      REPO:
        type: string
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Metabase Repo
        uses: actions/checkout@v4
        with:
          repository: metabase/metabase
          ref: ${{ inputs.MB_VERSION }}
      - uses: actions/checkout@v4
        with:
          path: registry
      - name: Checkout Driver Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.REPO }}
          path: modules/drivers/partner-driver

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21

      - name: Start Database in Docker
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "registry/docker-compose.yml"
          services: |
            ${{ inputs.DRIVER }}

      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1262.sh &&
          sudo bash ./linux-install-1.11.1.1262.sh

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "22"
          cache: "yarn"

      - name: Get M2 cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-partner-driver-${{ hashFiles('**/deps.edn') }}

      - name: Prepare stuff for pulses
        run: yarn build-static-viz
