name: Test Partner Driver

on:
  workflow_call:
    inputs:
      DRIVER:
        description: 'Driver to use'
        type: string
        required: true
      MB_REF:
        type: string
        required: true
      PARTNER_REF:
        type: string
        required: true
      REPO:
        type: string
        required: true
      DOCKER:
        type: boolean
        required: true

jobs:
  main:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./metabase
    steps:
      - uses: actions/checkout@v4
        with:
          path: registry

      - name: Checkout Metabase Repo
        uses: actions/checkout@v4
        with:
          path: metabase
          repository: metabase/metabase
          ref: ${{ inputs.MB_REF }}

      - name: Checkout Driver Repo
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.REPO }}
          path: metabase/modules/drivers/partner-driver
          ref: ${{ inputs.PARTNER_REF }}

      - name: Set up JDK 21
        uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 21

      - name: Start Database in Docker
        if: ${{ inputs.DOCKER }}
        uses: hoverkraft-tech/compose-action@v2.0.1
        with:
          compose-file: "./registry/docker-compose.yml"
          services: |
            ${{ inputs.DRIVER }}

      - name: Install Clojure CLI
        run: |
          curl -O https://download.clojure.org/install/linux-install-1.11.1.1262.sh &&
          sudo bash ./linux-install-1.11.1.1262.sh

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: "22"
          cache: "yarn"
          cache-dependency-path: ./metabase/yarn.lock

      - name: Get M2 cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.gitlibs
          key: ${{ runner.os }}-partner-driver-${{ hashFiles('**/deps.edn') }}

      - name: Build static-viz
        run: yarn build-static-viz

      - name: Run tests
        run: |

          sudo echo "127.0.0.1 ${{ inputs.DRIVER }}" | sudo tee -a /etc/hosts

          echo ${{ inputs.DOCKER }}

          DRIVERS=${{ inputs.DRIVER }} \
            clojure \
            -Sdeps "{:jvm-opts [\"-Dci=true\"] :aliases {:partner-driver {:extra-paths [\"modules/drivers/partner-driver/test\" \"modules/driver/partner-driver/src\"] :extra-deps {metabase/partner-driver {:local/root \"modules/drivers/partner-driver\"}}}}}" \
            -X:dev:drivers:drivers-dev:test:partner-driver \
            :only-tags [:mb/driver-tests]

      - name: Publish Test Report
        uses: dorny/test-reporter@v1
        if: failure()
        with:
          path: "metabase/target/junit/**/*_test.xml"
          name: JUnit Test Report ${{ inputs.DRIVER }}
          reporter: java-junit
          list-suites: failed
          list-tests: failed
          fail-on-error: false
