name: Test All Partner Drivers

on: push

jobs:
  clickhouse-edge:
    name: edge
    uses: ./.github/workflows/callable-partner-driver.yml
    with:
      MB_REF: 'master'
      PARTNER_REF: 'master'
      DRIVER: 'clickhouse'
      REPO: ClickHouse/metabase-clickhouse-driver
      DOCKER: true

  clickhouse-current:
    name: current
    uses: ./.github/workflows/callable-partner-driver.yml
    with:
      MB_REF: 'release-x.${{ vars.CURRENT_VERSION }}.x'
      PARTNER_REF: 'master'
      DRIVER: 'clickhouse'
      REPO: ClickHouse/metabase-clickhouse-driver
      DOCKER: true

  clickhouse-previous:
    name: previous
    uses: ./.github/workflows/callable-partner-driver.yml
    with:
      MB_REF: 'release-x.${{ vars.CURRENT_VERSION - 1 }}.x'
      PARTNER_REF: 'master'
      DRIVER: 'clickhouse'
      REPO: ClickHouse/metabase-clickhouse-driver
      DOCKER: true

  materialize:
    uses: ./.github/workflows/callable-partner-driver.yml
    with:
      MB_REF: 'master'
      PARTNER_REF: 'master'
      DRIVER: 'materialize'
      REPO: MaterializeInc/metabase-materialize-driver
      DOCKER: true

  ocient:
    uses: ./.github/workflows/callable-partner-driver.yml
    with:
      MB_REF: 'master'
      PARTNER_REF: 'master'
      DRIVER: 'ocient'
      REPO: Xeograph/metabase-ocient-driver
      DOCKER: false

  starburst:
    uses: ./.github/workflows/callable-partner-driver.yml
    with:
      MB_REF: 'master'
      PARTNER_REF: 'main'
      DRIVER: 'starburst'
      REPO: starburstdata/metabase-driver
      DOCKER: false
