name: Test Partner Driver

on: push

jobs:
  clickhouse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Test Athena driver
        uses: ./.github/actions/test-partner
        with:
          DRIVER: 'clickhouse'
          OP_SERVICE_ACCOUNT_TOKEN: ${{ secrets.OP_SERVICE_ACCOUNT_TOKEN }}
