name: Test All Partner Drivers

on: push

jobs:
  clickhouse:
    uses: ./.github/workflows/callable-partner-driver.yml
    with:
      MB_VERSION: 'master'
      DRIVER: 'clickhouse'
      REPO: ClickHouse/metabase-clickhouse-driver

  materialize:
    uses: ./.github/workflows/callable-partner-driver.yml
    with:
      MB_VERSION: 'master'
      DRIVER: 'materialize'
      REPO: MaterializeInc/metabase-materialize-driver
